# Generated by Django 3.2.6 on 2021-09-06 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='winningposition',
            name='prof',
        ),
        migrations.AddField(
            model_name='winningposition',
            name='prof',
            field=models.ManyToManyField(to='event_app.Profile'),
        ),
    ]
